title: Title test
description: Description test
theme: just-the-docs
dark_mode: true


url: https://janniswolf.github.io/testestest

aux_links:
  Template Repository: https://github.com/JannisWolf/testing_just-the-docs
